# Generated by Django 5.1.6 on 2025-04-10 07:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('donor_id', models.IntegerField(blank=True, null=True)),
                ('requires_transcript', models.BooleanField(default=False)),
                ('requires_recommendation', models.BooleanField(default=False)),
                ('min_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('allowed_major', models.CharField(blank=True, default='', max_length=255)),
                ('bookmarked_by', models.ManyToManyField(blank=True, related_name='saved_scholarships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
