# Generated by Django 5.1.6 on 2025-04-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scholarship',
            options={},
        ),
        migrations.AddField(
            model_name='scholarship',
            name='allowed_major',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        # migrations.AddField(
        #     model_name='scholarship',
        #     name='min_gpa',
        #     field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        # ),
        migrations.AddField(
            model_name='scholarship',
            name='requires_recommendation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='requires_transcript',
            field=models.BooleanField(default=False),
        ),
    ]
