# Generated by Django 5.1.6 on 2025-04-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='donor_id',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='donor_username',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
