# Generated by Django 5.1.6 on 2025-04-10 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0002_remove_scholarship_donor_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scholarship',
            options={'ordering': ['deadline']},
        ),
    ]
