# Generated by Django 5.1.6 on 2025-03-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0003_scholarship_is_active'),
    ]


