# Generated by Django 5.1.6 on 2025-04-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0003_alter_scholarship_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='donor_username',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='donor_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
