# Generated by Django 5.1.6 on 2025-04-09 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0002_alter_scholarship_options_scholarship_allowed_major_and_more'),
        ('scholarships', '0005_remove_scholarship_founder'),
    ]

    operations = [
    ]
