# Generated by Django 5.1.6 on 2025-04-15 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0004_remove_scholarship_donor_username_and_more'),
        ('scholarships', '0006_merge_20250409_0450'),
    ]

    operations = [
    ]
