# Generated by Django 5.1.6 on 2025-04-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0007_merge_20250415_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
