# Generated by Django 5.1.6 on 2025-04-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='awarded',
            field=models.BooleanField(default=False),
        ),
    ]
